// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTourProject.Models;

namespace TempleTourProject.Migrations
{
    [DbContext(typeof(TempleTourContext))]
    [Migration("20220323181023_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("TempleTourProject.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppointmentTime")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentTime = "8 AM"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentTime = "9 AM"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentTime = "10 AM"
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentTime = "11 AM"
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentTime = "12 AM"
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppointmentTime = "1 PM"
                        },
                        new
                        {
                            AppointmentId = 7,
                            AppointmentTime = "2 PM"
                        });
                });

            modelBuilder.Entity("TempleTourProject.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            AppointmentId = 1,
                            Date = "3/25/22",
                            Email = "sarahlolmstead999@gmail.com",
                            GroupName = "Sarah's Group",
                            GroupSize = 2,
                            Phone = "801-435-1276"
                        },
                        new
                        {
                            GroupId = 2,
                            AppointmentId = 2,
                            Date = "4/18/22",
                            Email = "profhilton@gmail.com",
                            GroupName = "Spencer's Group",
                            GroupSize = 8,
                            Phone = "385-789-6932"
                        });
                });

            modelBuilder.Entity("TempleTourProject.Models.Group", b =>
                {
                    b.HasOne("TempleTourProject.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
